my_blog/config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'

  resources :articles

  root 'articles#index'

end

my_blog/app/models/article.rb
class Article < ActiveRecord::Base
end

my_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

my_blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
  end

  def create
    @params = Article.new(params.require(:article).permit(:author, :text))
    @params.save
    redirect_to @params
    #render plain: params[:article].inspect
  end

  def show
    @article = Article.find(params[:id])
  end
end

my_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

my_blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

my_blog/app/views/articles/index.html.erb
<h1>Articles#index</h1>

<table class="table table-striped">
  
	<thead>
        <tr>
          <th>#</th>
          <th>Author</th>
          <th>Text</th>
          <th>Link</th>
        </tr>
    </thead>

  	<% @articles.each do |article| %>
	
    <tbody>
        <tr>
          <th scope="row"><%= article.id %></th>
          <td><%= article.author %></td>
          <td><%= article.text %></td>
          <td><%= link_to 'Show', article_path(article) %></td>
        </tr>
    </tbody>

  <% end %>
</table>

my_blog/app/views/articles/new.html.erb
<h1>New</h1>
<p>
	<%= bootstrap_form_for :article, url: articles_path do |f| %>
  	<%= f.text_field :author, label: 'Автор' %>
  	<%= f.text_area :text, label: 'Текст' %>
  	<%= f.submit "Log In", class: "btn btn-primary" %>
<% end %>
</p>

my_blog/app/views/articles/show.html.erb
<h1>show</h1>
<%= @article.author %>
<%= @article.text %>
<%= link_to "Index", articles_path %>

my_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
</head>
<body>

<%= yield %>

</body>
</html>